services:
 - type: web
   name: nextjs-static
   runtime: static
   buildCommand: yarn; yarn build
   publishPath: out
   pullRequestPreviewsEnabled: true
   envVars:
   - key: NODE_ENV
     value: production
